backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

publish_mode: editorial_workflow

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product ID", name: "id", widget: "number", required: true }
      - { label: "Product Name", name: "name", widget: "string", required: true }
      - { label: "Product Name (Bengali)", name: "name_bn", widget: "string", required: true }
      - { label: "Price (BDT)", name: "price", widget: "number", required: true, min: 0 }
      - { label: "Category", name: "category", widget: "select", required: true, options: ["Mugs", "T-Shirts", "Keychains", "Water Bottles", "Gift for Him", "Gift for Her", "Gift for Parents", "Gifts for Babies", "For Couple", "Premium Luxury Gift Hampers", "Chocolates & Flowers"] }
      - { label: "Product Image", name: "image", widget: "string", required: true, hint: "Enter image URL or upload image" }
      - { label: "Description", name: "description", widget: "text", required: true }
      - { label: "Description (Bengali)", name: "description_bn", widget: "text", required: true }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Stock Status", name: "in_stock", widget: "boolean", default: true }
      - { label: "Badge Text", name: "badge", widget: "string", required: false, hint: "Optional badge text like 'New', 'Sale', etc." }

  - name: "categories"
    label: "Categories"
    folder: "_categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Category ID", name: "id", widget: "number", required: true }
      - { label: "Category Name", name: "name", widget: "string", required: true }
      - { label: "Category Name (Bengali)", name: "name_bn", widget: "string", required: true }
      - { label: "Icon Class", name: "icon", widget: "string", required: true, hint: "Font Awesome icon class (e.g., fas fa-coffee)" }
      - { label: "Description", name: "description", widget: "text", required: true }
      - { label: "Sort Order", name: "sort_order", widget: "number", default: 0 }
      - { label: "Active", name: "active", widget: "boolean", default: true }

  - name: "site_settings"
    label: "Site Settings"
    files:
      - label: "Contact Information"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - { label: "WhatsApp Number", name: "whatsapp", widget: "string", default: "01747292277" }
          - { label: "Bkash/Nagad Number", name: "payment_number", widget: "string", default: "01747292277" }
          - { label: "Business Hours", name: "business_hours", widget: "string", default: "9:00 AM - 10:00 PM (Daily)" }
          - { label: "Email", name: "email", widget: "string", required: false }
          - { label: "Address", name: "address", widget: "text", required: false }

      - label: "Homepage Settings"
        name: "homepage"
        file: "_data/homepage.yml"
        fields:
          - label: "Hero Slides"
            name: "hero_slides"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "text" }
              - { label: "Button Text", name: "button_text", widget: "string" }
              - { label: "Button Action", name: "button_action", widget: "string" }
              - { label: "Image URL", name: "image", widget: "string" }
              - { label: "Active", name: "active", widget: "boolean", default: true }

          - label: "Featured Products"
            name: "featured_products"
            widget: "list"
            field: { label: "Product ID", name: "product_id", widget: "number" }

          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "Customer Name", name: "name", widget: "string" }
              - { label: "Review Text", name: "review", widget: "text" }
              - { label: "Rating", name: "rating", widget: "number", min: 1, max: 5, default: 5 }
              - { label: "Verified Buyer", name: "verified", widget: "boolean", default: true }

      - label: "Payment Settings"
        name: "payment"
        file: "_data/payment.yml"
        fields:
          - { label: "Advance Payment Amount", name: "advance_amount", widget: "number", default: 100 }
          - { label: "Payment Methods", name: "methods", widget: "list", field: { label: "Method", name: "method", widget: "string" } }
          - { label: "Payment Instructions", name: "instructions", widget: "text" }

# Configure Netlify Identity for user management
identity:
  create_user_access: invite_only
  login_url: /admin/

# Configure editor settings
editor:
  preview: true

# Configure media library
media_library:
  name: netlify
  config:
    multiple: true

# Configure slug settings
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# Configure local backend for development
local_backend: true

# Configure search
search: true

# Configure file collections for static data
media_folder_relative: true
